/// Offline copy of the website's preset themes, as served by
/// GET /platform-settings/public → `themes` (snapshot taken 2026-09-29).
///
/// Used only until the live list has been fetched once; after that the app
/// shows whatever the server returns (including admin-created themes).
const String kBundledWebThemesJson = r'''
[
 {
  "id": "paper",
  "name": "Paper",
  "mode": "light",
  "tokens": {
   "--bg-primary": "#f5f3ee",
   "--bg-secondary": "#fbfaf7",
   "--bg-tertiary": "#efede6",
   "--bg-card": "#fdfcfa",
   "--surface-elevated": "#ffffff",
   "--bg-code": "#f8f6f1",
   "--text-primary": "#191c1a",
   "--text-secondary": "#464e48",
   "--text-muted": "#5f6861",
   "--primary": "#0e7a4b",
   "--primary-hover": "#0b6640",
   "--primary-light": "#128b58",
   "--accent-color": "#0e7a4b",
   "--btn-primary-bg": "#0e7a4b",
   "--btn-primary-text": "#ffffff",
   "--success-color": "#167540",
   "--warning-color": "#98570a",
   "--danger-color": "#b5342d",
   "--info-color": "#2f62b8",
   "--difficulty-easy": "#167540",
   "--difficulty-medium": "#98570a",
   "--difficulty-hard": "#b5342d",
   "--border-color": "#e3dfd4",
   "--border-strong": "#d2cdbe",
   "--font-primary": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
   "--font-display": "'Fraunces', 'Newsreader', 'Iowan Old Style', Georgia, serif"
  }
 },
 {
  "id": "paper-dark",
  "name": "Charcoal",
  "mode": "dark",
  "tokens": {
   "--bg-primary": "#0e1110",
   "--bg-secondary": "#131615",
   "--bg-tertiary": "#191d1b",
   "--bg-card": "#141816",
   "--surface-elevated": "#1a1f1c",
   "--bg-code": "#101312",
   "--text-primary": "#e8ebe8",
   "--text-secondary": "#b9bfb9",
   "--text-muted": "#8d958d",
   "--primary": "#34c58a",
   "--primary-hover": "#52d29c",
   "--primary-light": "#6bddae",
   "--accent-color": "#34c58a",
   "--btn-primary-bg": "#34c58a",
   "--btn-primary-text": "#04140c",
   "--success-color": "#4acb84",
   "--warning-color": "#e6a93b",
   "--danger-color": "#ef7b72",
   "--info-color": "#6ea4ee",
   "--difficulty-easy": "#4acb84",
   "--difficulty-medium": "#e6a93b",
   "--difficulty-hard": "#ef7b72",
   "--border-color": "#252a27",
   "--border-strong": "#363d39",
   "--font-primary": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
   "--font-display": "'Fraunces', 'Newsreader', 'Iowan Old Style', Georgia, serif"
  }
 },
 {
  "id": "sepia",
  "name": "Warm Light",
  "mode": "light",
  "tokens": {
   "--bg-primary": "#f6f1e6",
   "--bg-secondary": "#f0e8d5",
   "--bg-tertiary": "#eadfc9",
   "--bg-card": "#fffefb",
   "--surface-elevated": "#ffffff",
   "--bg-code": "#f3ebd9",
   "--text-primary": "#2a241d",
   "--text-secondary": "#5c5344",
   "--text-muted": "#897f6d",
   "--primary": "#5b4331",
   "--primary-hover": "#47331f",
   "--primary-light": "#7a6047",
   "--accent-color": "#5b4331",
   "--btn-primary-bg": "#3a2c20",
   "--btn-primary-text": "#f7f3ea",
   "--success-color": "#4a7c52",
   "--warning-color": "#a9781f",
   "--danger-color": "#a5442f",
   "--info-color": "#3f6a86",
   "--difficulty-easy": "#4a7c52",
   "--difficulty-medium": "#a9781f",
   "--difficulty-hard": "#a5442f",
   "--border-color": "#e7ddc5",
   "--border-strong": "#d6c9ab",
   "--font-primary": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
   "--font-display": "'Fraunces', 'Newsreader', 'Iowan Old Style', Georgia, serif"
  }
 },
 {
  "id": "sepia-dark",
  "name": "Warm Dark",
  "mode": "dark",
  "tokens": {
   "--bg-primary": "#14100a",
   "--bg-secondary": "#1c1710",
   "--bg-tertiary": "#171209",
   "--bg-card": "#241d14",
   "--surface-elevated": "#2c2419",
   "--bg-code": "#0f0c07",
   "--text-primary": "#f5efe3",
   "--text-secondary": "#c1b39b",
   "--text-muted": "#948871",
   "--primary": "#e0bf98",
   "--primary-hover": "#ecceac",
   "--primary-light": "#ecd4b8",
   "--accent-color": "#e0bf98",
   "--btn-primary-bg": "#efe0c6",
   "--btn-primary-text": "#1a150e",
   "--success-color": "#7cc08d",
   "--warning-color": "#dcae63",
   "--danger-color": "#e58c72",
   "--info-color": "#82b4d2",
   "--difficulty-easy": "#7cc08d",
   "--difficulty-medium": "#dcae63",
   "--difficulty-hard": "#e58c72",
   "--border-color": "#372c1b",
   "--border-strong": "#4c3d29",
   "--font-primary": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
   "--font-display": "'Fraunces', 'Newsreader', 'Iowan Old Style', Georgia, serif"
  }
 },
 {
  "id": "mono-light",
  "name": "Monochrome Light",
  "mode": "light",
  "tokens": {
   "--bg-primary": "#ffffff",
   "--bg-secondary": "#f4f4f4",
   "--bg-tertiary": "#e8e8e8",
   "--bg-card": "#ffffff",
   "--bg-code": "#f4f4f4",
   "--text-primary": "#111111",
   "--text-secondary": "#3f3f3f",
   "--text-muted": "#6b6b6b",
   "--primary": "#111111",
   "--primary-hover": "#000000",
   "--primary-light": "#333333",
   "--accent-color": "#111111",
   "--btn-primary-bg": "#111111",
   "--btn-primary-text": "#ffffff",
   "--success-color": "#3a3a3a",
   "--warning-color": "#6b6b6b",
   "--danger-color": "#000000",
   "--info-color": "#333333",
   "--difficulty-easy": "#6b6b6b",
   "--difficulty-medium": "#3f3f3f",
   "--difficulty-hard": "#000000",
   "--border-color": "#d9d9d9",
   "--font-primary": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
   "--font-display": "'Fraunces', 'Newsreader', 'Iowan Old Style', Georgia, serif"
  }
 },
 {
  "id": "mono-dark",
  "name": "Monochrome Dark",
  "mode": "dark",
  "tokens": {
   "--bg-primary": "#0a0a0a",
   "--bg-secondary": "#121212",
   "--bg-tertiary": "#1a1a1a",
   "--bg-card": "#121212",
   "--bg-code": "#141414",
   "--text-primary": "#ffffff",
   "--text-secondary": "#b5b5b5",
   "--text-muted": "#888888",
   "--primary": "#ffffff",
   "--primary-hover": "#dcdcdc",
   "--primary-light": "#f5f5f5",
   "--accent-color": "#ffffff",
   "--btn-primary-bg": "#ffffff",
   "--btn-primary-text": "#0a0a0a",
   "--success-color": "#e5e5e5",
   "--warning-color": "#a0a0a0",
   "--danger-color": "#ffffff",
   "--info-color": "#b5b5b5",
   "--difficulty-easy": "#d0d0d0",
   "--difficulty-medium": "#9a9a9a",
   "--difficulty-hard": "#ffffff",
   "--border-color": "#262626",
   "--font-primary": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
   "--font-display": "'Fraunces', 'Newsreader', 'Iowan Old Style', Georgia, serif"
  }
 },
 {
  "id": "midnight",
  "name": "Midnight Blue",
  "mode": "dark",
  "tokens": {
   "--bg-primary": "#0b1120",
   "--bg-secondary": "#111a2e",
   "--bg-tertiary": "#1a2540",
   "--bg-card": "#111a2e",
   "--bg-code": "#0f1830",
   "--text-primary": "#e8edf7",
   "--text-secondary": "#9fb0cc",
   "--text-muted": "#6b7c99",
   "--primary": "#7aa2ff",
   "--primary-hover": "#5f8cf0",
   "--primary-light": "#f5f5f5",
   "--accent-color": "#7aa2ff",
   "--btn-primary-bg": "#3b6fe0",
   "--btn-primary-text": "#ffffff",
   "--success-color": "#e5e5e5",
   "--warning-color": "#a0a0a0",
   "--danger-color": "#ffffff",
   "--info-color": "#b5b5b5",
   "--difficulty-easy": "#d0d0d0",
   "--difficulty-medium": "#9a9a9a",
   "--difficulty-hard": "#ffffff",
   "--border-color": "#22304d",
   "--font-primary": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
   "--font-display": "'Fraunces', 'Newsreader', 'Iowan Old Style', Georgia, serif"
  }
 }
]
''';
